In [1]:
import os
import sys

In [2]:
!pip install pymysql

Requirement already satisfied: pymysql in g:\scripts\mlds\.env\lib\site-packages (1.0.2)

# Connect DB

In [3]:
class Config:
    MYSQL_HOST = '34.136.184.58'
    MYSQL_PORT = 3306 
    MYSQL_USER = 'r2de2'
    MYSQL_PASSWORD = 'I_Love_Data_Engineer'
    MYSQL_DB = 'r2de2'
    MYSQL_CHARSET = 'utf8mb4'

In [4]:
import pymysql

In [5]:
connection = pymysql.connect(host=Config.MYSQL_HOST,
                            port=Config.MYSQL_PORT,
                            user=Config.MYSQL_USER,
                            passwd=Config.MYSQL_PASSWORD,
                            db=Config.MYSQL_DB,
                            charset=Config.MYSQL_CHARSET,
                            cursorclass=pymysql.cursors.DictCursor)

In [6]:
connection

In [7]:
cursor = connection.cursor()
cursor.execute("SHOW TABLES;")
table = cursor.fetchall()
cursor.close()
print(table)

[{'Tables_in_r2de2': 'audible_data'}, {'Tables_in_r2de2': 'audible_transaction'}]

In [8]:
with connection.cursor() as cursor:
    cursor.execute("SELECT * FROM  audible_data;")
    data = cursor.fetchall()

In [9]:
type(data)

list

# Convert to Pandas

In [10]:
import pandas as pd

In [11]:
df = pd.DataFrame(data)
df

,Book_ID,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price
0,1,Bamboozled by Jesus,How God Tricked Me into the Life of My Dreams,Yvonne Orji,Yvonne Orji,6 hrs and 31 mins,Unabridged Audiobook,Biographies & Memoirs,5,47.0,$29.65
1,2,Sixth Realm Part 1,"A LitRPG Fantasy Series (The Ten Realms, Book 6)",Michael Chatfield,Neil Hellegers,13 hrs and 33 mins,Unabridged Audiobook,Science Fiction & Fantasy,4.5,98.0,$24.95
2,3,Go Tell the Bees That I Am Gone,"Outlander, Book 9",Diana Gabaldon,Davina Porter,27 hrs and 30 mins,Unabridged Audiobook,Science Fiction & Fantasy,None,NaN,$41.99
3,4,How the Word Is Passed,A Reckoning with the History of Slavery Across...,Clint Smith,Clint Smith,10 hrs and 7 mins,Unabridged Audiobook,History,None,NaN,$29.65
4,5,The Devil May Dance,A Novel,Jake Tapper,Rob Shapiro,10 hrs and 12 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.5,108.0,$29.65
...,...,...,...,...,...,...,...,...,...,...,...
2264,2265,Kama Sutra,Become a Master of the Art of Love Making. Tan...,Eva Becker,ChasMandala,3 hrs and 29 mins,Unabridged Audiobook,Erotica,5,203.0,$14.95
2265,2266,Meditación Práctica para Principiantes [Prac...,Una guía para principiantes para aliviar la an...,Taylor Knox,William Ditilio,3 hrs and 14 mins,Unabridged Audiobook,Health & Wellness,5,203.0,$14.95
2266,2267,Forgotten,"The Untold Story of D-day's Black Heroes, at H...",Linda Hervieux,Ron Butler,9 hrs and 33 mins,Unabridged Audiobook,History,4.6,70.0,$24.95
2267,2268,The Missing,None,Daisy Pearce,Karen Cass,10 hrs and 18 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.2,141.0,$30.09
2268,2269,Becoming,None,Michelle Obama,Michelle Obama,19 hrs and 3 mins,Unabridged Audiobook,Biographies & Memoirs,4.9,167195.0,$35.71

In [12]:
audible_data = df.set_index("Book_ID")

In [13]:
audible_data

,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price
Book_ID,,,,,,,,,,
1,Bamboozled by Jesus,How God Tricked Me into the Life of My Dreams,Yvonne Orji,Yvonne Orji,6 hrs and 31 mins,Unabridged Audiobook,Biographies & Memoirs,5,47.0,$29.65
2,Sixth Realm Part 1,"A LitRPG Fantasy Series (The Ten Realms, Book 6)",Michael Chatfield,Neil Hellegers,13 hrs and 33 mins,Unabridged Audiobook,Science Fiction & Fantasy,4.5,98.0,$24.95
3,Go Tell the Bees That I Am Gone,"Outlander, Book 9",Diana Gabaldon,Davina Porter,27 hrs and 30 mins,Unabridged Audiobook,Science Fiction & Fantasy,None,NaN,$41.99
4,How the Word Is Passed,A Reckoning with the History of Slavery Across...,Clint Smith,Clint Smith,10 hrs and 7 mins,Unabridged Audiobook,History,None,NaN,$29.65
5,The Devil May Dance,A Novel,Jake Tapper,Rob Shapiro,10 hrs and 12 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.5,108.0,$29.65
...,...,...,...,...,...,...,...,...,...,...
2265,Kama Sutra,Become a Master of the Art of Love Making. Tan...,Eva Becker,ChasMandala,3 hrs and 29 mins,Unabridged Audiobook,Erotica,5,203.0,$14.95
2266,Meditación Práctica para Principiantes [Prac...,Una guía para principiantes para aliviar la an...,Taylor Knox,William Ditilio,3 hrs and 14 mins,Unabridged Audiobook,Health & Wellness,5,203.0,$14.95
2267,Forgotten,"The Untold Story of D-day's Black Heroes, at H...",Linda Hervieux,Ron Butler,9 hrs and 33 mins,Unabridged Audiobook,History,4.6,70.0,$24.95
2268,The Missing,None,Daisy Pearce,Karen Cass,10 hrs and 18 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.2,141.0,$30.09
2269,Becoming,None,Michelle Obama,Michelle Obama,19 hrs and 3 mins,Unabridged Audiobook,Biographies & Memoirs,4.9,167195.0,$35.71

In [14]:
with connection.cursor() as cursor:
    cursor.execute("SELECT * FROM  audible_transaction;")
    transaction = cursor.fetchall()

In [15]:
audible_transaction = pd.DataFrame(transaction)
audible_transaction

                  timestamp   user_id  book_id                   country
0       2021-05-01 00:00:01  ad8eca41     1584                  Portugal
1       2021-05-01 00:00:03  561b26c1      829  United States of America
2       2021-05-01 00:00:04  81f149e5     1391                     Japan
3       2021-05-01 00:00:07  4f218413     1586                    Taiwan
4       2021-05-01 00:00:18  a4066781      300  United States of America
...                     ...       ...      ...                       ...
1998816 2021-07-31 23:59:47  72da1411      600                  Portugal
1998817 2021-07-31 23:59:48  620c27c8      462                Montenegro
1998818 2021-07-31 23:59:55  84fe88ab     1656  United States of America
1998819 2021-07-31 23:59:57  fd6cc4fc      522  United States of America
1998820 2021-07-31 23:59:59  9f4d5e3b      110  United States of America

[1998821 rows x 4 columns]

In [16]:
transaction = audible_transaction.merge(audible_data, how="left", left_on="book_id", right_on="Book_ID")

In [17]:
transaction

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,None,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,$35.00
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,$19.59
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,$31.50
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,None,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,$19.95
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,$17.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998816,2021-07-31 23:59:47,72da1411,600,Portugal,The Time of Contempt,"The Witcher, Book 2",Andrzej Sapkowski,Peter Kenny,11 hrs and 55 mins,Unabridged Audiobook,Science Fiction & Fantasy,4.7,14344.0,$25.08
1998817,2021-07-31 23:59:48,620c27c8,462,Montenegro,Endurance,Shackleton's Incredible Voyage,Alfred Lansing,Simon Prebble,10 hrs and 20 mins,Unabridged Audiobook,History,4.7,18764.0,$24.95
1998818,2021-07-31 23:59:55,84fe88ab,1656,United States of America,The Spy and the Traitor,The Greatest Espionage Story of the Cold War,Ben Macintyre,John Lee,13 hrs and 20 mins,Unabridged Audiobook,Biographies & Memoirs,4.8,7150.0,$31.95
1998819,2021-07-31 23:59:57,fd6cc4fc,522,United States of America,Lilac Girls,A Novel,Martha Hall Kelly,Cassandra Campbell,17 hrs and 30 mins,Unabridged Audiobook,Literature & Fiction,4.7,19401.0,$31.50
1998820,2021-07-31 23:59:59,9f4d5e3b,110,United States of America,Unfu*k Yourself,Get Out of Your Head and into Your Life,Gary John Bishop,Gary John Bishop,3 hrs and 24 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.6,73022.0,$20.52

## REST API

In [18]:
!pip install requests

Requirement already satisfied: requests in g:\scripts\mlds\.env\lib\site-packages (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in g:\scripts\mlds\.env\lib\site-packages (from requests) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in g:\scripts\mlds\.env\lib\site-packages (from requests) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in g:\scripts\mlds\.env\lib\site-packages (from requests) (2022.6.15)
Requirement already satisfied: charset-normalizer<3,>=2 in g:\scripts\mlds\.env\lib\site-packages (from requests) (2.0.4)

In [19]:
import requests
import pandas as pd

In [20]:
url = " https://r2de2-workshop-vmftiryt6q-ts.a.run.app/usd_thb_conversion_rate"

In [21]:
get_r = requests.get(url)

In [22]:
result_conversion_rates = get_r.json()

In [23]:
assert isinstance(result_conversion_rates, dict)

In [24]:
conversion_rate = pd.DataFrame(result_conversion_rates)
conversion_rate

            conversion_rate
2021-04-01           31.194
2021-04-02           31.290
2021-04-03           31.256
2021-04-04           31.244
2021-04-05           31.342
...                     ...
2021-08-08           33.395
2021-08-09           33.464
2021-08-10           33.460
2021-08-11           33.145
2021-08-12           33.084

[134 rows x 1 columns]

In [25]:
conversion_rate = conversion_rate.reset_index().rename(columns={"index": "date"})
conversion_rate.head(5)

         date  conversion_rate
0  2021-04-01           31.194
1  2021-04-02           31.290
2  2021-04-03           31.256
3  2021-04-04           31.244
4  2021-04-05           31.342

In [33]:
transaction['date'] = pd.to_datetime(transaction['timestamp']).dt.date

In [34]:
conversion_rate['date'] = pd.to_datetime(conversion_rate['date']).dt.date

In [35]:
transaction.head(1)

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,data,date
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,None,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,$35.00,2021-05-01,2021-05-01

In [36]:
 final_df = transaction.merge(conversion_rate, how="left", left_on="date", right_on="date")

In [37]:
final_df

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,data_x,date,conversion_rate,data_y
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,None,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,$35.00,2021-05-01,2021-05-01,31.140,2021-05-01
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,$19.59,2021-05-01,2021-05-01,31.140,2021-05-01
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,$31.50,2021-05-01,2021-05-01,31.140,2021-05-01
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,None,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,$19.95,2021-05-01,2021-05-01,31.140,2021-05-01
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,$17.49,2021-05-01,2021-05-01,31.140,2021-05-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998816,2021-07-31 23:59:47,72da1411,600,Portugal,The Time of Contempt,"The Witcher, Book 2",Andrzej Sapkowski,Peter Kenny,11 hrs and 55 mins,Unabridged Audiobook,Science Fiction & Fantasy,4.7,14344.0,$25.08,2021-07-31,2021-07-31,32.887,2021-07-31
1998817,2021-07-31 23:59:48,620c27c8,462,Montenegro,Endurance,Shackleton's Incredible Voyage,Alfred Lansing,Simon Prebble,10 hrs and 20 mins,Unabridged Audiobook,History,4.7,18764.0,$24.95,2021-07-31,2021-07-31,32.887,2021-07-31
1998818,2021-07-31 23:59:55,84fe88ab,1656,United States of America,The Spy and the Traitor,The Greatest Espionage Story of the Cold War,Ben Macintyre,John Lee,13 hrs and 20 mins,Unabridged Audiobook,Biographies & Memoirs,4.8,7150.0,$31.95,2021-07-31,2021-07-31,32.887,2021-07-31
1998819,2021-07-31 23:59:57,fd6cc4fc,522,United States of America,Lilac Girls,A Novel,Martha Hall Kelly,Cassandra Campbell,17 hrs and 30 mins,Unabridged Audiobook,Literature & Fiction,4.7,19401.0,$31.50,2021-07-31,2021-07-31,32.887,2021-07-31
1998820,2021-07-31 23:59:59,9f4d5e3b,110,United States of America,Unfu*k Yourself,Get Out of Your Head and into Your Life,Gary John Bishop,Gary John Bishop,3 hrs and 24 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.6,73022.0,$20.52,2021-07-31,2021-07-31,32.887,2021-07-31

In [58]:
final_df["Price"] = final_df.apply(lambda x:x['Price'].replace("$", ""), axis=1)
final_df.head(5)

AttributeError: 'float' object has no attribute 'replace'

In [41]:
final_df["Price"] = final_df["Price"].astype(float)

In [ ]:
def convert_rate(price, rate):
    return price * rate

final_df["THBPrice"] = final_df.apply(lambda x:x['Price'] * x["conversion_rate"], axis=1)
final_df["THBPrice"] = final_df.apply(lambda x: convert_rate(x["Price"], x["conversion_rate"], axis=1))

In [50]:
final_df = final_df.drop('date', axis=1)

In [57]:
final_df

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,conversion_rate,THBPrice
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,None,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,35.00,31.140,1089.90000
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,19.59,31.140,610.03260
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,31.50,31.140,980.91000
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,None,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,19.95,31.140,621.24300
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,17.49,31.140,544.63860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998816,2021-07-31 23:59:47,72da1411,600,Portugal,The Time of Contempt,"The Witcher, Book 2",Andrzej Sapkowski,Peter Kenny,11 hrs and 55 mins,Unabridged Audiobook,Science Fiction & Fantasy,4.7,14344.0,25.08,32.887,824.80596
1998817,2021-07-31 23:59:48,620c27c8,462,Montenegro,Endurance,Shackleton's Incredible Voyage,Alfred Lansing,Simon Prebble,10 hrs and 20 mins,Unabridged Audiobook,History,4.7,18764.0,24.95,32.887,820.53065
1998818,2021-07-31 23:59:55,84fe88ab,1656,United States of America,The Spy and the Traitor,The Greatest Espionage Story of the Cold War,Ben Macintyre,John Lee,13 hrs and 20 mins,Unabridged Audiobook,Biographies & Memoirs,4.8,7150.0,31.95,32.887,1050.73965
1998819,2021-07-31 23:59:57,fd6cc4fc,522,United States of America,Lilac Girls,A Novel,Martha Hall Kelly,Cassandra Campbell,17 hrs and 30 mins,Unabridged Audiobook,Literature & Fiction,4.7,19401.0,31.50,32.887,1035.94050
1998820,2021-07-31 23:59:59,9f4d5e3b,110,United States of America,Unfu*k Yourself,Get Out of Your Head and into Your Life,Gary John Bishop,Gary John Bishop,3 hrs and 24 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.6,73022.0,20.52,32.887,674.84124

In [59]:
file = final_df.to_csv("final_df.csv", index=False)

## .env

In [1]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in g:\scripts\mlds\.env\lib\site-packages (0.21.0)

In [7]:
import os
from dotenv import load_dotenv
load_dotenv()

True

In [4]:
%%writefile .env
MYSQL_HOST = '34.136.184.58'
MYSQL_PORT = 3306 
MYSQL_USER = 'r2de2'
MYSQL_PASSWORD = 'I_Love_Data_Engineer'
MYSQL_DB = 'r2de2'
MYSQL_CHARSET = 'utf8mb4'

UsageError: %%writefile is a cell magic, but the cell body is empty.

'34.136.184.58'